# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipeline_control_pb2 as pipeline__control__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pipeline_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PipelineControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFlags = channel.unary_unary(
                '/xrcomm.PipelineControl/GetFlags',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.PipelineFlags.FromString,
                _registered_method=True)
        self.SetFullPacketMode = channel.unary_unary(
                '/xrcomm.PipelineControl/SetFullPacketMode',
                request_serializer=pipeline__control__pb2.BoolRequest.SerializeToString,
                response_deserializer=pipeline__control__pb2.PipelineFlags.FromString,
                _registered_method=True)
        self.SetLogging = channel.unary_unary(
                '/xrcomm.PipelineControl/SetLogging',
                request_serializer=pipeline__control__pb2.BoolRequest.SerializeToString,
                response_deserializer=pipeline__control__pb2.PipelineFlags.FromString,
                _registered_method=True)
        self.SetIpMode = channel.unary_unary(
                '/xrcomm.PipelineControl/SetIpMode',
                request_serializer=pipeline__control__pb2.BoolRequest.SerializeToString,
                response_deserializer=pipeline__control__pb2.PipelineFlags.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/xrcomm.PipelineControl/GetStats',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.CombinedStats.FromString,
                _registered_method=True)
        self.ListSecondaryIPs = channel.unary_unary(
                '/xrcomm.PipelineControl/ListSecondaryIPs',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.SecondaryIPList.FromString,
                _registered_method=True)
        self.WatchStatus = channel.unary_stream(
                '/xrcomm.PipelineControl/WatchStatus',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.PipelineStatus.FromString,
                _registered_method=True)
        self.SetReadCapture = channel.unary_unary(
                '/xrcomm.PipelineControl/SetReadCapture',
                request_serializer=pipeline__control__pb2.ReadCaptureRequest.SerializeToString,
                response_deserializer=pipeline__control__pb2.ReadConfig.FromString,
                _registered_method=True)
        self.SetReadCaptureRate = channel.unary_unary(
                '/xrcomm.PipelineControl/SetReadCaptureRate',
                request_serializer=pipeline__control__pb2.ReadCaptureRateRequest.SerializeToString,
                response_deserializer=pipeline__control__pb2.ReadConfig.FromString,
                _registered_method=True)
        self.GetReadConfig = channel.unary_unary(
                '/xrcomm.PipelineControl/GetReadConfig',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.ReadConfig.FromString,
                _registered_method=True)
        self.GetReadStatus = channel.unary_unary(
                '/xrcomm.PipelineControl/GetReadStatus',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.ReadStatus.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/xrcomm.PipelineControl/Shutdown',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.StatusReply.FromString,
                _registered_method=True)


class PipelineControlServicer:
    """Missing associated documentation comment in .proto file."""

    def GetFlags(self, request, context):
        """── Mode flags ──────────────────────────────────────────────────────────
        Read current mode flags
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFullPacketMode(self, request, context):
        """Set individual flags — all modes are INDEPENDENT, no mutual exclusion
        FULL_PACKET_MODE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLogging(self, request, context):
        """NVMe logging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIpMode(self, request, context):
        """IQ_MODE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """── Stats ────────────────────────────────────────────────────────────────
        Combined stats: pipeline counters + per-channel telemetry + per-IP dispatch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecondaryIPs(self, request, context):
        """List all registered secondary IQ applications
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchStatus(self, request, context):
        """── Live streaming ───────────────────────────────────────────────────────
        1 Hz streaming status (flags + stats + uptime)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReadCapture(self, request, context):
        """── NVMe auto-read configuration ─────────────────────────────────────────
        Per-channel read configuration written to the configured read_config.ini.
        The platform performs one read pass after SetLogging(off), reading only
        the channels that captured data this session.
        start_ts + duration for one channel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReadCaptureRate(self, request, context):
        """sample_rate for one channel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReadConfig(self, request, context):
        """all 8 channel rows
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReadStatus(self, request, context):
        """live auto-read progress
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """── Control ──────────────────────────────────────────────────────────────
        Graceful pipeline shutdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFlags': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlags,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.PipelineFlags.SerializeToString,
            ),
            'SetFullPacketMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFullPacketMode,
                    request_deserializer=pipeline__control__pb2.BoolRequest.FromString,
                    response_serializer=pipeline__control__pb2.PipelineFlags.SerializeToString,
            ),
            'SetLogging': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLogging,
                    request_deserializer=pipeline__control__pb2.BoolRequest.FromString,
                    response_serializer=pipeline__control__pb2.PipelineFlags.SerializeToString,
            ),
            'SetIpMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIpMode,
                    request_deserializer=pipeline__control__pb2.BoolRequest.FromString,
                    response_serializer=pipeline__control__pb2.PipelineFlags.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.CombinedStats.SerializeToString,
            ),
            'ListSecondaryIPs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecondaryIPs,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.SecondaryIPList.SerializeToString,
            ),
            'WatchStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchStatus,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.PipelineStatus.SerializeToString,
            ),
            'SetReadCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReadCapture,
                    request_deserializer=pipeline__control__pb2.ReadCaptureRequest.FromString,
                    response_serializer=pipeline__control__pb2.ReadConfig.SerializeToString,
            ),
            'SetReadCaptureRate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReadCaptureRate,
                    request_deserializer=pipeline__control__pb2.ReadCaptureRateRequest.FromString,
                    response_serializer=pipeline__control__pb2.ReadConfig.SerializeToString,
            ),
            'GetReadConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReadConfig,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.ReadConfig.SerializeToString,
            ),
            'GetReadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReadStatus,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.ReadStatus.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.StatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xrcomm.PipelineControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xrcomm.PipelineControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFlags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetFlags',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.PipelineFlags.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFullPacketMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetFullPacketMode',
            pipeline__control__pb2.BoolRequest.SerializeToString,
            pipeline__control__pb2.PipelineFlags.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLogging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetLogging',
            pipeline__control__pb2.BoolRequest.SerializeToString,
            pipeline__control__pb2.PipelineFlags.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetIpMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetIpMode',
            pipeline__control__pb2.BoolRequest.SerializeToString,
            pipeline__control__pb2.PipelineFlags.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetStats',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.CombinedStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSecondaryIPs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/ListSecondaryIPs',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.SecondaryIPList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xrcomm.PipelineControl/WatchStatus',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.PipelineStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetReadCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetReadCapture',
            pipeline__control__pb2.ReadCaptureRequest.SerializeToString,
            pipeline__control__pb2.ReadConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetReadCaptureRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetReadCaptureRate',
            pipeline__control__pb2.ReadCaptureRateRequest.SerializeToString,
            pipeline__control__pb2.ReadConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReadConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetReadConfig',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.ReadConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetReadStatus',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.ReadStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/Shutdown',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
