# XRComm Playback configuration — edit values, do not rename keys

core_list = 7,8,9 # DPDK lcore IDs to use for packet transmission, e.g. 7,8,9

source_mode = 1              # 0 = NVMe streaming (SPDK), 1 = file playback (.bin)

binary_filename = tone_512.bin   # inputs/playback_waveforms/

target_sample_rate_hz = 800000000 # 800 MS/s = 800 MHz, 1.47456 GS/s = 1.47456 GHz

tx_port_id = 0 # DPDK port ID to transmit Port 0 = hsp 1 and Port 1 = hsp 2

dest_mac = 14:FE:B5:DD:9A:82 # destination MAC address for transmitted packets, e.g. 14:FE:B5:DD:9A:82

loop_count = 0               # 0 = infinite looping of the input file, N > 0 loops the input file N times

trigger_burst_size = 1       # 'T' key marks next N packets ACTIVE (0x01000000), then IDLE