# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipeline_control_pb2 as pipeline__control__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pipeline_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PipelineControlStub(object):
    """============================================================================
    --- Platform mode / stats RPCs (Sections 8.1 / 8.2) merge in here ---
    rpc GetFlags          (Empty)       returns (PipelineFlags);
    rpc SetDspMode        (BoolRequest) returns (PipelineFlags);
    rpc SetLogging        (BoolRequest) returns (PipelineFlags);
    rpc SetIpMode         (BoolRequest) returns (PipelineFlags);
    rpc GetStats          (Empty)       returns (CombinedStats);
    rpc ListSecondaryIPs  (Empty)       returns (SecondaryIPList);
    rpc WatchStatus       (Empty)       returns (stream PipelineStatus);
    rpc Shutdown          (Empty)       returns (StatusReply);
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPlaybackConfig = channel.unary_unary(
                '/xrcomm.PipelineControl/GetPlaybackConfig',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetCoreList = channel.unary_unary(
                '/xrcomm.PipelineControl/GetCoreList',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.CoreListValue.FromString,
                _registered_method=True)
        self.SetCoreList = channel.unary_unary(
                '/xrcomm.PipelineControl/SetCoreList',
                request_serializer=pipeline__control__pb2.CoreListValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetSourceMode = channel.unary_unary(
                '/xrcomm.PipelineControl/GetSourceMode',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.SourceModeValue.FromString,
                _registered_method=True)
        self.SetSourceMode = channel.unary_unary(
                '/xrcomm.PipelineControl/SetSourceMode',
                request_serializer=pipeline__control__pb2.SourceModeValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetBinaryFilename = channel.unary_unary(
                '/xrcomm.PipelineControl/GetBinaryFilename',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.BinaryFilenameValue.FromString,
                _registered_method=True)
        self.SetBinaryFilename = channel.unary_unary(
                '/xrcomm.PipelineControl/SetBinaryFilename',
                request_serializer=pipeline__control__pb2.BinaryFilenameValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetSampleRate = channel.unary_unary(
                '/xrcomm.PipelineControl/GetSampleRate',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.SampleRateValue.FromString,
                _registered_method=True)
        self.SetSampleRate = channel.unary_unary(
                '/xrcomm.PipelineControl/SetSampleRate',
                request_serializer=pipeline__control__pb2.SampleRateValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetTxPortId = channel.unary_unary(
                '/xrcomm.PipelineControl/GetTxPortId',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.TxPortIdValue.FromString,
                _registered_method=True)
        self.SetTxPortId = channel.unary_unary(
                '/xrcomm.PipelineControl/SetTxPortId',
                request_serializer=pipeline__control__pb2.TxPortIdValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetDestMac = channel.unary_unary(
                '/xrcomm.PipelineControl/GetDestMac',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.DestMacValue.FromString,
                _registered_method=True)
        self.SetDestMac = channel.unary_unary(
                '/xrcomm.PipelineControl/SetDestMac',
                request_serializer=pipeline__control__pb2.DestMacValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetLoopCount = channel.unary_unary(
                '/xrcomm.PipelineControl/GetLoopCount',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.LoopCountValue.FromString,
                _registered_method=True)
        self.SetLoopCount = channel.unary_unary(
                '/xrcomm.PipelineControl/SetLoopCount',
                request_serializer=pipeline__control__pb2.LoopCountValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetTriggerBurstSize = channel.unary_unary(
                '/xrcomm.PipelineControl/GetTriggerBurstSize',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.TriggerBurstSizeValue.FromString,
                _registered_method=True)
        self.SetTriggerBurstSize = channel.unary_unary(
                '/xrcomm.PipelineControl/SetTriggerBurstSize',
                request_serializer=pipeline__control__pb2.TriggerBurstSizeValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.StartPlayback = channel.unary_unary(
                '/xrcomm.PipelineControl/StartPlayback',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.StatusReply.FromString,
                _registered_method=True)
        self.StopPlayback = channel.unary_unary(
                '/xrcomm.PipelineControl/StopPlayback',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetPlaybackDiagnostics = channel.unary_unary(
                '/xrcomm.PipelineControl/GetPlaybackDiagnostics',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackDiagnostics.FromString,
                _registered_method=True)
        self.WatchPlaybackDiagnostics = channel.unary_stream(
                '/xrcomm.PipelineControl/WatchPlaybackDiagnostics',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackDiagnostics.FromString,
                _registered_method=True)


class PipelineControlServicer(object):
    """============================================================================
    --- Platform mode / stats RPCs (Sections 8.1 / 8.2) merge in here ---
    rpc GetFlags          (Empty)       returns (PipelineFlags);
    rpc SetDspMode        (BoolRequest) returns (PipelineFlags);
    rpc SetLogging        (BoolRequest) returns (PipelineFlags);
    rpc SetIpMode         (BoolRequest) returns (PipelineFlags);
    rpc GetStats          (Empty)       returns (CombinedStats);
    rpc ListSecondaryIPs  (Empty)       returns (SecondaryIPList);
    rpc WatchStatus       (Empty)       returns (stream PipelineStatus);
    rpc Shutdown          (Empty)       returns (StatusReply);
    """

    def GetPlaybackConfig(self, request, context):
        """--- Playback configuration: snapshot + 16 per-field RPCs (Section 8.3) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoreList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCoreList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSourceMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSourceMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBinaryFilename(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBinaryFilename(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSampleRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSampleRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTxPortId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTxPortId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDestMac(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDestMac(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoopCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLoopCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTriggerBurstSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTriggerBurstSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPlayback(self, request, context):
        """--- Playback start/stop + diagnostics (Section 8.4) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPlayback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaybackDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchPlaybackDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPlaybackConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaybackConfig,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetCoreList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoreList,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.CoreListValue.SerializeToString,
            ),
            'SetCoreList': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCoreList,
                    request_deserializer=pipeline__control__pb2.CoreListValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetSourceMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSourceMode,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.SourceModeValue.SerializeToString,
            ),
            'SetSourceMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSourceMode,
                    request_deserializer=pipeline__control__pb2.SourceModeValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetBinaryFilename': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBinaryFilename,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.BinaryFilenameValue.SerializeToString,
            ),
            'SetBinaryFilename': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBinaryFilename,
                    request_deserializer=pipeline__control__pb2.BinaryFilenameValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetSampleRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSampleRate,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.SampleRateValue.SerializeToString,
            ),
            'SetSampleRate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSampleRate,
                    request_deserializer=pipeline__control__pb2.SampleRateValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetTxPortId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTxPortId,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.TxPortIdValue.SerializeToString,
            ),
            'SetTxPortId': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTxPortId,
                    request_deserializer=pipeline__control__pb2.TxPortIdValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetDestMac': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDestMac,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.DestMacValue.SerializeToString,
            ),
            'SetDestMac': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDestMac,
                    request_deserializer=pipeline__control__pb2.DestMacValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetLoopCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoopCount,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.LoopCountValue.SerializeToString,
            ),
            'SetLoopCount': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLoopCount,
                    request_deserializer=pipeline__control__pb2.LoopCountValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetTriggerBurstSize': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTriggerBurstSize,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.TriggerBurstSizeValue.SerializeToString,
            ),
            'SetTriggerBurstSize': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTriggerBurstSize,
                    request_deserializer=pipeline__control__pb2.TriggerBurstSizeValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'StartPlayback': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPlayback,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.StatusReply.SerializeToString,
            ),
            'StopPlayback': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPlayback,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.StatusReply.SerializeToString,
            ),
            'GetPlaybackDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaybackDiagnostics,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackDiagnostics.SerializeToString,
            ),
            'WatchPlaybackDiagnostics': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchPlaybackDiagnostics,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackDiagnostics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xrcomm.PipelineControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xrcomm.PipelineControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineControl(object):
    """============================================================================
    --- Platform mode / stats RPCs (Sections 8.1 / 8.2) merge in here ---
    rpc GetFlags          (Empty)       returns (PipelineFlags);
    rpc SetDspMode        (BoolRequest) returns (PipelineFlags);
    rpc SetLogging        (BoolRequest) returns (PipelineFlags);
    rpc SetIpMode         (BoolRequest) returns (PipelineFlags);
    rpc GetStats          (Empty)       returns (CombinedStats);
    rpc ListSecondaryIPs  (Empty)       returns (SecondaryIPList);
    rpc WatchStatus       (Empty)       returns (stream PipelineStatus);
    rpc Shutdown          (Empty)       returns (StatusReply);
    """

    @staticmethod
    def GetPlaybackConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetPlaybackConfig',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoreList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetCoreList',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.CoreListValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCoreList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetCoreList',
            pipeline__control__pb2.CoreListValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSourceMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetSourceMode',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.SourceModeValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSourceMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetSourceMode',
            pipeline__control__pb2.SourceModeValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBinaryFilename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetBinaryFilename',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.BinaryFilenameValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBinaryFilename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetBinaryFilename',
            pipeline__control__pb2.BinaryFilenameValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSampleRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetSampleRate',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.SampleRateValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSampleRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetSampleRate',
            pipeline__control__pb2.SampleRateValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTxPortId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetTxPortId',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.TxPortIdValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTxPortId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetTxPortId',
            pipeline__control__pb2.TxPortIdValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDestMac(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetDestMac',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.DestMacValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDestMac(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetDestMac',
            pipeline__control__pb2.DestMacValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoopCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetLoopCount',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.LoopCountValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLoopCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetLoopCount',
            pipeline__control__pb2.LoopCountValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTriggerBurstSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetTriggerBurstSize',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.TriggerBurstSizeValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTriggerBurstSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetTriggerBurstSize',
            pipeline__control__pb2.TriggerBurstSizeValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPlayback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/StartPlayback',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPlayback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/StopPlayback',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaybackDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetPlaybackDiagnostics',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.PlaybackDiagnostics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchPlaybackDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xrcomm.PipelineControl/WatchPlaybackDiagnostics',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.PlaybackDiagnostics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
