# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipeline_control_pb2 as pipeline__control__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pipeline_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlaybackControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPlaybackConfig = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/GetPlaybackConfig',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetCoreList = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/GetCoreList',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.CoreListValue.FromString,
                _registered_method=True)
        self.SetCoreList = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/SetCoreList',
                request_serializer=pipeline__control__pb2.CoreListValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetSourceMode = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/GetSourceMode',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.SourceModeValue.FromString,
                _registered_method=True)
        self.SetSourceMode = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/SetSourceMode',
                request_serializer=pipeline__control__pb2.SourceModeValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetSampleRate = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/GetSampleRate',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.SampleRateValue.FromString,
                _registered_method=True)
        self.SetSampleRate = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/SetSampleRate',
                request_serializer=pipeline__control__pb2.SampleRateValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetLoopCount = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/GetLoopCount',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.LoopCountValue.FromString,
                _registered_method=True)
        self.SetLoopCount = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/SetLoopCount',
                request_serializer=pipeline__control__pb2.LoopCountValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetTriggerBurstSize = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/GetTriggerBurstSize',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.TriggerBurstSizeValue.FromString,
                _registered_method=True)
        self.SetTriggerBurstSize = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/SetTriggerBurstSize',
                request_serializer=pipeline__control__pb2.TriggerBurstSizeValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetChannelFilename = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/GetChannelFilename',
                request_serializer=pipeline__control__pb2.ChannelRef.SerializeToString,
                response_deserializer=pipeline__control__pb2.ChannelFilenameValue.FromString,
                _registered_method=True)
        self.SetChannelFilename = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/SetChannelFilename',
                request_serializer=pipeline__control__pb2.ChannelFilenameValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetTxPortId = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/GetTxPortId',
                request_serializer=pipeline__control__pb2.PortRef.SerializeToString,
                response_deserializer=pipeline__control__pb2.TxPortIdValue.FromString,
                _registered_method=True)
        self.SetTxPortId = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/SetTxPortId',
                request_serializer=pipeline__control__pb2.TxPortIdValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.GetDestMac = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/GetDestMac',
                request_serializer=pipeline__control__pb2.PortRef.SerializeToString,
                response_deserializer=pipeline__control__pb2.DestMacValue.FromString,
                _registered_method=True)
        self.SetDestMac = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/SetDestMac',
                request_serializer=pipeline__control__pb2.DestMacValue.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackConfig.FromString,
                _registered_method=True)
        self.StartPlayback = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/StartPlayback',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.StatusReply.FromString,
                _registered_method=True)
        self.StopPlayback = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/StopPlayback',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetPlaybackDiagnostics = channel.unary_unary(
                '/xrcomm.playback.v8t8r.PlaybackControl/GetPlaybackDiagnostics',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackDiagnostics.FromString,
                _registered_method=True)
        self.WatchPlaybackDiagnostics = channel.unary_stream(
                '/xrcomm.playback.v8t8r.PlaybackControl/WatchPlaybackDiagnostics',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.PlaybackDiagnostics.FromString,
                _registered_method=True)


class PlaybackControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPlaybackConfig(self, request, context):
        """whole-snapshot read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoreList(self, request, context):
        """scalar fields: dedicated Get/Set, each Set writes ONLY its own key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCoreList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSourceMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSourceMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSampleRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSampleRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoopCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLoopCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTriggerBurstSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTriggerBurstSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannelFilename(self, request, context):
        """per-channel waveform (8T8R: channels 0..7) — writes only ch<n>_filename
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetChannelFilename(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTxPortId(self, request, context):
        """per-port fields (ports 0..1) — writes only port<n>_tx_port_id / port<n>_dest_mac
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTxPortId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDestMac(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDestMac(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPlayback(self, request, context):
        """process control (gRPC error if already in the requested state)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPlayback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaybackDiagnostics(self, request, context):
        """steady-state diagnostics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchPlaybackDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaybackControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPlaybackConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaybackConfig,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetCoreList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoreList,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.CoreListValue.SerializeToString,
            ),
            'SetCoreList': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCoreList,
                    request_deserializer=pipeline__control__pb2.CoreListValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetSourceMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSourceMode,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.SourceModeValue.SerializeToString,
            ),
            'SetSourceMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSourceMode,
                    request_deserializer=pipeline__control__pb2.SourceModeValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetSampleRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSampleRate,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.SampleRateValue.SerializeToString,
            ),
            'SetSampleRate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSampleRate,
                    request_deserializer=pipeline__control__pb2.SampleRateValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetLoopCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoopCount,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.LoopCountValue.SerializeToString,
            ),
            'SetLoopCount': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLoopCount,
                    request_deserializer=pipeline__control__pb2.LoopCountValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetTriggerBurstSize': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTriggerBurstSize,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.TriggerBurstSizeValue.SerializeToString,
            ),
            'SetTriggerBurstSize': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTriggerBurstSize,
                    request_deserializer=pipeline__control__pb2.TriggerBurstSizeValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetChannelFilename': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannelFilename,
                    request_deserializer=pipeline__control__pb2.ChannelRef.FromString,
                    response_serializer=pipeline__control__pb2.ChannelFilenameValue.SerializeToString,
            ),
            'SetChannelFilename': grpc.unary_unary_rpc_method_handler(
                    servicer.SetChannelFilename,
                    request_deserializer=pipeline__control__pb2.ChannelFilenameValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetTxPortId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTxPortId,
                    request_deserializer=pipeline__control__pb2.PortRef.FromString,
                    response_serializer=pipeline__control__pb2.TxPortIdValue.SerializeToString,
            ),
            'SetTxPortId': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTxPortId,
                    request_deserializer=pipeline__control__pb2.TxPortIdValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'GetDestMac': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDestMac,
                    request_deserializer=pipeline__control__pb2.PortRef.FromString,
                    response_serializer=pipeline__control__pb2.DestMacValue.SerializeToString,
            ),
            'SetDestMac': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDestMac,
                    request_deserializer=pipeline__control__pb2.DestMacValue.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackConfig.SerializeToString,
            ),
            'StartPlayback': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPlayback,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.StatusReply.SerializeToString,
            ),
            'StopPlayback': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPlayback,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.StatusReply.SerializeToString,
            ),
            'GetPlaybackDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaybackDiagnostics,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackDiagnostics.SerializeToString,
            ),
            'WatchPlaybackDiagnostics': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchPlaybackDiagnostics,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.PlaybackDiagnostics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xrcomm.playback.v8t8r.PlaybackControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xrcomm.playback.v8t8r.PlaybackControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaybackControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPlaybackConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/GetPlaybackConfig',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoreList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/GetCoreList',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.CoreListValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCoreList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/SetCoreList',
            pipeline__control__pb2.CoreListValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSourceMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/GetSourceMode',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.SourceModeValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSourceMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/SetSourceMode',
            pipeline__control__pb2.SourceModeValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSampleRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/GetSampleRate',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.SampleRateValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSampleRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/SetSampleRate',
            pipeline__control__pb2.SampleRateValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoopCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/GetLoopCount',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.LoopCountValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLoopCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/SetLoopCount',
            pipeline__control__pb2.LoopCountValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTriggerBurstSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/GetTriggerBurstSize',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.TriggerBurstSizeValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTriggerBurstSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/SetTriggerBurstSize',
            pipeline__control__pb2.TriggerBurstSizeValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannelFilename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/GetChannelFilename',
            pipeline__control__pb2.ChannelRef.SerializeToString,
            pipeline__control__pb2.ChannelFilenameValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetChannelFilename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/SetChannelFilename',
            pipeline__control__pb2.ChannelFilenameValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTxPortId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/GetTxPortId',
            pipeline__control__pb2.PortRef.SerializeToString,
            pipeline__control__pb2.TxPortIdValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTxPortId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/SetTxPortId',
            pipeline__control__pb2.TxPortIdValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDestMac(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/GetDestMac',
            pipeline__control__pb2.PortRef.SerializeToString,
            pipeline__control__pb2.DestMacValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDestMac(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/SetDestMac',
            pipeline__control__pb2.DestMacValue.SerializeToString,
            pipeline__control__pb2.PlaybackConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPlayback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/StartPlayback',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPlayback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/StopPlayback',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaybackDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/GetPlaybackDiagnostics',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.PlaybackDiagnostics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchPlaybackDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xrcomm.playback.v8t8r.PlaybackControl/WatchPlaybackDiagnostics',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.PlaybackDiagnostics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
