# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipeline_control_pb2 as pipeline__control__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pipeline_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PipelineControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFlags = channel.unary_unary(
                '/xrcomm.PipelineControl/GetFlags',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.PipelineFlags.FromString,
                _registered_method=True)
        self.SetDspMode = channel.unary_unary(
                '/xrcomm.PipelineControl/SetDspMode',
                request_serializer=pipeline__control__pb2.BoolRequest.SerializeToString,
                response_deserializer=pipeline__control__pb2.PipelineFlags.FromString,
                _registered_method=True)
        self.SetLogging = channel.unary_unary(
                '/xrcomm.PipelineControl/SetLogging',
                request_serializer=pipeline__control__pb2.BoolRequest.SerializeToString,
                response_deserializer=pipeline__control__pb2.PipelineFlags.FromString,
                _registered_method=True)
        self.SetIpMode = channel.unary_unary(
                '/xrcomm.PipelineControl/SetIpMode',
                request_serializer=pipeline__control__pb2.BoolRequest.SerializeToString,
                response_deserializer=pipeline__control__pb2.PipelineFlags.FromString,
                _registered_method=True)
        self.SetReadCapture = channel.unary_unary(
                '/xrcomm.PipelineControl/SetReadCapture',
                request_serializer=pipeline__control__pb2.ReadCaptureRequest.SerializeToString,
                response_deserializer=pipeline__control__pb2.StatusReply.FromString,
                _registered_method=True)
        self.SetReadCaptureRate = channel.unary_unary(
                '/xrcomm.PipelineControl/SetReadCaptureRate',
                request_serializer=pipeline__control__pb2.ReadRateRequest.SerializeToString,
                response_deserializer=pipeline__control__pb2.StatusReply.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/xrcomm.PipelineControl/Shutdown',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/xrcomm.PipelineControl/GetStats',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.CombinedStats.FromString,
                _registered_method=True)
        self.GetModeStats = channel.unary_unary(
                '/xrcomm.PipelineControl/GetModeStats',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.ModeStats.FromString,
                _registered_method=True)
        self.ListSecondaryIPs = channel.unary_unary(
                '/xrcomm.PipelineControl/ListSecondaryIPs',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.SecondaryIPList.FromString,
                _registered_method=True)
        self.WatchStatus = channel.unary_stream(
                '/xrcomm.PipelineControl/WatchStatus',
                request_serializer=pipeline__control__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__control__pb2.PipelineStatus.FromString,
                _registered_method=True)


class PipelineControlServicer:
    """Missing associated documentation comment in .proto file."""

    def GetFlags(self, request, context):
        """Read current mode flags
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDspMode(self, request, context):
        """Set individual flags (returns new state; modes are independent — no
        mutual exclusion, any combination may be enabled simultaneously)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLogging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIpMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReadCapture(self, request, context):
        """NVMe read-back config (overwrites common/read_config.ini). After a
        gRPC SetLogging(false) stop, the primary auto-reads this many seconds of
        the latest capture out of NVMe (size = seconds * sample_rate_hz * 4).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReadCaptureRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Graceful pipeline shutdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Combined stats: pipeline + per-IP dispatch + DSP secondary + spectrum IPs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModeStats(self, request, context):
        """Per-API-mode stats: Rx / processed / drops for FULL_PACKET, IQ and
        LOG_BLOCK modes, plus per external IP application.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecondaryIPs(self, request, context):
        """List all registered secondary IPs (in-process and out-of-process)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchStatus(self, request, context):
        """1 Hz streaming status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFlags': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlags,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.PipelineFlags.SerializeToString,
            ),
            'SetDspMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDspMode,
                    request_deserializer=pipeline__control__pb2.BoolRequest.FromString,
                    response_serializer=pipeline__control__pb2.PipelineFlags.SerializeToString,
            ),
            'SetLogging': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLogging,
                    request_deserializer=pipeline__control__pb2.BoolRequest.FromString,
                    response_serializer=pipeline__control__pb2.PipelineFlags.SerializeToString,
            ),
            'SetIpMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIpMode,
                    request_deserializer=pipeline__control__pb2.BoolRequest.FromString,
                    response_serializer=pipeline__control__pb2.PipelineFlags.SerializeToString,
            ),
            'SetReadCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReadCapture,
                    request_deserializer=pipeline__control__pb2.ReadCaptureRequest.FromString,
                    response_serializer=pipeline__control__pb2.StatusReply.SerializeToString,
            ),
            'SetReadCaptureRate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReadCaptureRate,
                    request_deserializer=pipeline__control__pb2.ReadRateRequest.FromString,
                    response_serializer=pipeline__control__pb2.StatusReply.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.StatusReply.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.CombinedStats.SerializeToString,
            ),
            'GetModeStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModeStats,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.ModeStats.SerializeToString,
            ),
            'ListSecondaryIPs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecondaryIPs,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.SecondaryIPList.SerializeToString,
            ),
            'WatchStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchStatus,
                    request_deserializer=pipeline__control__pb2.Empty.FromString,
                    response_serializer=pipeline__control__pb2.PipelineStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xrcomm.PipelineControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xrcomm.PipelineControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFlags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetFlags',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.PipelineFlags.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDspMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetDspMode',
            pipeline__control__pb2.BoolRequest.SerializeToString,
            pipeline__control__pb2.PipelineFlags.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLogging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetLogging',
            pipeline__control__pb2.BoolRequest.SerializeToString,
            pipeline__control__pb2.PipelineFlags.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetIpMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetIpMode',
            pipeline__control__pb2.BoolRequest.SerializeToString,
            pipeline__control__pb2.PipelineFlags.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetReadCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetReadCapture',
            pipeline__control__pb2.ReadCaptureRequest.SerializeToString,
            pipeline__control__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetReadCaptureRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/SetReadCaptureRate',
            pipeline__control__pb2.ReadRateRequest.SerializeToString,
            pipeline__control__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/Shutdown',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetStats',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.CombinedStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModeStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/GetModeStats',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.ModeStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSecondaryIPs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrcomm.PipelineControl/ListSecondaryIPs',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.SecondaryIPList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xrcomm.PipelineControl/WatchStatus',
            pipeline__control__pb2.Empty.SerializeToString,
            pipeline__control__pb2.PipelineStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)